<?php
/* Smarty version 5.4.0, created on 2024-08-19 04:39:41
  from 'file:html-content.tpl' */

/* @var \Smarty\Template $_smarty_tpl */
if ($_smarty_tpl->getCompiled()->isFresh($_smarty_tpl, array (
  'version' => '5.4.0',
  'unifunc' => 'content_66c2cc8d613416_01020688',
  'has_nocache_code' => false,
  'file_dependency' => 
  array (
    '8e8e009a1ea4363af8898aa070d6d90e51ad063b' => 
    array (
      0 => 'html-content.tpl',
      1 => 1724042365,
      2 => 'file',
    ),
  ),
  'includes' => 
  array (
  ),
))) {
function content_66c2cc8d613416_01020688 (\Smarty\Template $_smarty_tpl) {
$_smarty_current_dir = 'C:\\apache\\htdocs\\demo-site\\templates';
?><section class="header-image"><img id="html5-img" src="graphics/html5.png" alt="html5 logo"></section>
<section class="documentation-source">
    <div>Documentation: <a href="https://developer.mozilla.org/en-US/docs/Web/HTML">https://developer.mozilla.org/en-US/docs/Web/HTML</a></div>
</section>
<section>
    <p>HTML stands for Hypertext Markup Language and it is the skeleton of every website on the internet. It provides clear and concise, semantic sectioning of every element on the page, in a way that forms the Document Object Model (DOM). The browser and each of it's rendering engines <i>(depending on browser)</i>, CSS, Javascript, and anything else that needs to interact with the webpage can do so easily from the DOM concept, as long as it is properly marked with HTML in accordance with proper conventions and standards. Properly marked up webpages allows for cleaner and well maintained code across every other component of a website.</p>
</section>
<section>
    <p>According to Mozilla Developer Network(MDN), there are 142 HTML tags. However, only 115 are functional with the other 27 being deprecated or obsolete. Each of the HTML tags has different functionalities across semantic purposes that help define the structure of HTML documents designed to be displayed in a web browser.</p>
</section><br>
<section id="html-elements" class="example-content"> <!-- this section below was stolen from another website and needs updated formatting -->
    <p>Related: <span><a href="/list-of-html-entity-names-and-numbers"><svg width="25" height="16"><g fill="none" stroke-width="1"><path d="m18,1 6,7 -6,7"/><path d="M10,15 15,1"/><path d="M7,1 1,8 7,15"/></g></svg> <abbr title="Hypertext Markup Language">HTML</abbr> Entity Reference</a></span></p>
<p><strong><a href="/html-comment-element">&lt;!–- -–&gt;</a></strong><span></span> For commenting out sections of <abbr title="Hypertext Markup Language">HTML</abbr> or placing comments within <abbr title="Hypertext Markup Language">HTML</abbr>. Anything between &lt;!-- and --&gt; wont be rendered as text when the page loads in a web browser, but will still be visible if looking at the plain 'ol <abbr title="Hypertext Markup Language">HTML</abbr> file in a text editor.</p>
<p><strong><a href="/html-document-type-doctype-declaration">&lt;!DOCTYPE html></a></strong><span></span> Basically tells the browser what kind of document we're loading, in this case good 'ol <abbr title="Hypertext Markup Language">HTML</abbr>. This guy likes to be the first element in the document, even before the opening <code>&lt;html></code> tag. This page, for example, starts things off with <code>&lt;!DOCTYPE&nbsp;html></code></p>
<p><strong><code>&lt;a></code></strong><span></span> a for anchor, also known as a hyperlink, or simply a link. To make an actual link using the &lt;a> tag, use the href attribute: <code>&lt;a&nbsp;<span>href=</span>"<span>http://eastmanreference.com</span>"><span>Link</span>&lt;/a></code></p>
<p><a href="/html-abbreviation-abbr-element"><strong>&lt;abbr></strong></a><span></span> <abbr title="abbreviation">Abbr</abbr> is an abbreviation for abbreviation. Use it with the title attribute to define abbreviations. <code>&lt;abbr </code><code>title="Cascading Style Sheets"><abbr title="Cascading Style Sheets">CSS</abbr>&lt;/abbr></code>. Safari 12.0 hovering the mouse over <abbr title="Cascading Style Sheets">CSS</abbr> brings up a little tool tip generated by the abbreviation tag.</p>
<p><strong><code>&lt;address></code></strong><span></span> Contact information for the author. Alternatively, this could be general contact information for the website.</p>
<p><strong><code>&lt;area></code></strong><span></span> Establishes areas in an image map. &lt;area> is always used inside of &lt;map>.</p>
<p><strong><code>&lt;article></code></strong><span></span> The &lt;article> tag is new in HTML5. This tag can be used to contain blog entries, forum posts, etc.</p>
<p><strong><code>&lt;aside></code></strong><span></span> New in HTML5. The &lt;aside> element is for making sidebars that are placed next to the main content.</p>
<p><strong><code>&lt;audio></code></strong><span></span> New in HTML5. The &lt;audio> tag can be used to place an audio stream within an <abbr title="Hypertext Markup Language">HTML</abbr> document.</p>
<p><strong><a href="/html-bold-b-element">&lt;b></a></strong><span></span> For bolding or otherwise styling text without conveying any additional meaning such as with <code>&lt;em></code> and <code>&lt;strong></code> and etc.</p>
<p><strong><code>&lt;base></code></strong><span></span> Use to set a base URL.</p>
<p><strong><code>&lt;bdi></code></strong><span></span> Short for bidirectional isolation. Useful for working with languages that use right to left text.</p>
<p><strong><code>&lt;bdo></code></strong><span></span> Short for Bidirectional Override. Use this to override the current direction of text. Useful for languages that use right to left text.</p>
<p><strong><code>&lt;blockquote></code></strong><span></span> For quoting from an external source. Typically rendered as indented text.</p>
<p><strong><code>&lt;body></code></strong><span></span> Establishes the body of an <abbr title="Hypertext Markup Language">HTML</abbr> document.</p>
<p><a href="/html-line-break-br-element"><strong>&lt;br></strong></a><span></span> Single line break. Think of br as short for break.</p>
<p><strong><code>&lt;button></code></strong><span></span> Specifies button that can be clicked. Commonly used with forms.</p>
<p><strong><code>&lt;canvas></code></strong><span></span> Used for rendering graphics on the fly, typically in conjunction with a scripting language.</p>
<p><strong><code>&lt;caption></code></strong><span></span> Placed just after <code>&lt;table></code>, used for table caption.</p>
<p><strong><code>&lt;cite></code></strong><span></span> For citing.</p>
<p><strong><a href="/html-code-element">&lt;code></a></strong><span></span> For code examples. A little bit like <code>&lt;samp></code> and <code>&lt;kbd></code>, but specifically for code.</p>
<p><strong><code>&lt;col></code></strong><span></span> Specify properties of a <code>&lt;col></code> within a <code>&lt;colgroup></code></p>
<p><strong><code>&lt;colgroup></code></strong><span></span> Essentially a group of columns.</p>
<p><strong><code>&lt;data></code></strong><span></span> Used for script friendly data.</p>
<p><strong><code>&lt;datalist></code></strong><span></span> New in HTML5. Specify predefined data for an <code>&lt;input></code>.</p>
<p><strong><code>&lt;dd></code></strong><span></span> For description lists. Use with <code>&lt;dt></code> and <code>&lt;dl></code>.</p>
<p><strong><code>&lt;del></code></strong><span></span> Mark text as deleted without actually deleting it. This will typically be rendered as a strikethrough.</p>
<p><strong><code>&lt;details></code></strong><span></span> New in HTML5. Can be used for additional details which can be hidden or revealed.</p>
<p><strong><code>&lt;dfn></code></strong><span></span> Use when first defining a term.</p>
<p><strong><code>&lt;dialog></code></strong><span></span> Dialog box.</p>
<p><strong><code>&lt;div></code></strong><span></span> A divider or a kind of generic container.</p>
<p><strong><code>&lt;dl></code></strong><span></span> Description list. Use with <code>&lt;dd></code> and <code>&lt;dt></code>.</p>
<p><strong><code>&lt;dt></code></strong><span></span> Description list. Use with <code&lt;dd></code> and <code>&lt;dl></code>.</p>
<p><strong><code>&lt;em></code></strong><span></span> Emphasis, which I believe often defaults to italics. For something stronger, use <code>&lt;strong></code>.</p>
<p><strong><code>&lt;embed></code></strong><span></span> New in HTML5. A container for external content.</p>
<p><strong><code>&lt;fieldset></code></strong><span></span> Group related items in a form.</p>
<p><strong><code>&lt;figure></code></strong><span></span> Define self contained content such as photos or diagrams.</p>
<p><strong><code>&lt;footer></code></strong><span></span> The footer of a document, below the main content.</p>
<p><strong><code>&lt;form></code></strong><span></span> Forms for user input.</p>
<p><strong><code>&lt;h1></code></strong><span></span> Level 1 heading, the headline or title of a page.</p>
<p><strong><code>&lt;h2></code></strong><span></span> Level 2 heading, the subtitles of a page.</p>
<p><strong><code>&lt;h3></code></strong><span></span> Level 3 heading.</p>
<p><strong><code>&lt;h4></code></strong><span></span> Level 4 heading.</p>
<p><strong><code>&lt;h5></code></strong><span></span> Level 5 heading.</p>
<p><strong><code>&lt;h6></code></strong><span></span> Level 6 heading.</p>
<p><strong><code>&lt;head></code></strong><span></span> The head section. Used mostly for metadata.</p>
<p><strong><code>&lt;header></code></strong><span></span> Not to be confused with <code>&lt;head></code>, <code>&lt;header></code> typically contains introductory content and layout that goes above the body.</p>
<p><strong><code>&lt;hgroup></code></strong><span></span> Used for grouping <code>&lt;h1></code>, <code>&lt;h2></code>, <code>&lt;h3></code>, etc., tags together. Useful for multilevel headings.</p>
<p><strong><code>&lt;hr></code></strong><span></span> This can be used for separating text within a paragraph. Typically renders as a horizontal line running across the page.</p>
<p><strong><a href="html-element">&lt;html></a></strong><span></span> The root level tag of an <abbr title="Hypertext Markup Language">HTML</abbr> document. All other <abbr title="Hypertext Markup Language">HTML</abbr> tags go inside the <abbr title="Hypertext Markup Language">HTML</abbr> tag.</p>
<p><strong><code>&lt;i></code></strong><span></span> The <code>&lt;i></code> element has changed a little in HTML5. It can still make text italicized, and I think that is often the default behavior, however, this depends on the stylesheet.</p>
<p><strong><code>&lt;iframe></code></strong><span></span> Makes it possible to embed another page within a page. In HTML5 this is known as nested browsing.</p>
<p><a href="/html-image-img-element"><strong>&lt;img></a></strong><span></span> For displaying images on a webpage. Example: <code>&lt;img&nbsp;src="image.png"></code></p>
<p><strong><code>&lt;input></code></strong><span></span> Input is used with various attributes to create form input elements.</p>
<p><strong><code>&lt;ins></code></strong><span></span> Useful for denoting text that has been added to an <abbr title="Hypertext Markup Language">HTML</abbr> file since the original version. Updates to a blog post for example. This is typically rendered as underlined text, although this can really be rendered just about any way you want with a stylesheet.</p>
<p><a href="/html-keyboard-input-kbd-element"><strong>&lt;kbd></strong></a><span></span> Used for keyboard input. This is different from form element text input.</p>
<p><strong><code>&lt;keygen></code></strong><span></span> Used for authentication with a security certificate.</p>
<p><strong><code>&lt;label></code></strong><span></span> For assigning labels to interface elements such as forms.</p>
<p><strong><code>&lt;legend></code></strong><span></span> Useful for making forms easier to understand.</p>
<p><strong><code>&lt;li></code></strong><span></span> This represents a list item with an <code>&lt;ol></code> (ordered list) or <code>&lt;ul></code> (unordered list).</p>
<p><strong><code>&lt;link></code></strong><span></span> Used for linking to external resources. Typically seen in <code>&lt;head></code> referring to an external style sheet. Different from the <code>&lt;a></code> (anchor) tag.</p>
<p><strong><code>&lt;main></code></strong><span></span> New to HTML5. These tags enclose the main content of an <abbr title="Hypertext Markup Language">HTML</abbr> document.</p>
<p><strong><code>&lt;map></code></strong><span></span> Used when defining an image map.</p>
<p><strong><code>&lt;mark></code></strong><span></span> This is essentially used for highlighting. Of course, whether or not highlighting is actually involved depends on the involved stylesheet.</p>
<p><strong><code>&lt;menu></code></strong><span></span> Used for creating various kinds of menus. This is new to <abbr title="Hypertext Markup Language">HTML</abbr> 5.1.</p>
<p><strong><code>&lt;menuitem></code></strong><span></span> Specify actions that can be taken with a menu.</p>
<p><strong><code>&lt;meta></code></strong><span></span> Used for specifying various meta information about the document. Meta tags are used within the document <code>&lt;head></code>.</p>
<p><strong><code>&lt;meter></code></strong><span></span> Used to represent a number when the minimum and maximum is known, for example 10%.</p>
<p><strong><code>&lt;nav></code></strong><span></span> Used for specifying a navigational region within a document.</p>
<p><strong><code>&lt;noscript></code></strong><span></span> For anyone using scripts within their pages, <code>&lt;noscript></code> is useful for specifying content that should be rendered when scripting isn’t supported.</p>
<p><strong><code>&lt;object></code></strong><span></span> For embedding objects within a document.</p>
<p><strong><code>&lt;ol></code></strong><span></span> Ordered list (1. 2. 3.). Use with list&nbsp;item&nbsp;<code>&lt;li></code>.</p>
<p><strong><code>&lt;optgroup></code></strong><span></span> For grouping objects.</p>
<p><strong><code>&lt;option></code></strong><span></span> Used within the <code>&lt;select></code> tag to specify an option.</p>
<p><strong><code>&lt;output></code></strong><span></span> Displays the output of an action, such as from a script or form.</p>
<p><strong><a href="/html-paragraph-p-element">&lt;p></a></strong><span></span> Paragraph. Enclose paragraphs in an article within <code>&lt;p></code> tags.</p>
<p><strong><code>&lt;param></code></strong><span></span> Use when parameters need to be passed to an object embedded within the document.</p>
<p><strong><code>&lt;pre></code></strong><span></span> For preformatted text. This can be useful for demonstrating code, especially if there are multiple lines.</p>
<p><strong><code>&lt;progress></code></strong><span></span> Display the progress of an action, such as with a script.</p>
<p><strong><code>&lt;q></code></strong><span></span> Quote from some source.</p>
<p><strong><code>&lt;rb></code></strong><span></span> For Ruby annotations.</p>
<p><strong><code>&lt;rp></code></strong><span></span> Specify text to be displayed when Ruby annotations are not supported by the browser.</p>
<p><strong><code>&lt;rt></code></strong><span></span> Text component of a Ruby annotation.</p>
<p><strong><code>&lt;rtc></code></strong><span></span> Ruby Text Container.</p>
<p><strong><code>&lt;ruby></code></strong><span></span> Also used for Ruby annotation.</p>
<p><strong><code>&lt;s></code></strong><span></span> For marking up text that is not longer relevant, applicable, or accurate.</p>
<p><a href="html-sample-output-samp-element"><strong>&lt;samp></strong></a><span></span> Sample output one might get from a particular computer program.</p>
<p><strong><code>&lt;script></code></strong><span></span> Scripts inside of an <abbr title="Hypertext Markup Language">HTML</abbr> document are enclosed in the script tags.</p>
<p><strong><code>&lt;section></code></strong><span></span> A nonspecific means of breaking up content within a webpage into sections.</p>
<p><strong><code>&lt;select></code></strong><span></span> Used with <code>&lt;option></code> for selecting a particular option.</p>
<p><strong><code>&lt;small></code></strong><span></span> Typically used for small print. Useful for comments within the main content.</p>
<p><strong><code>&lt;source></code></strong><span></span> Used with <code>&lt;audio></code> and <code>&lt;video></code> for specifying media source.</p>
<p><strong><code>&lt;span></code></strong><span></span> Useful for applying styles to or around text, especially inline.</p>
<p><strong><code>&lt;strong></code></strong><span></span> The enclosed text is of strong importance.</p>
<p><strong><code>&lt;style></code></strong><span></span> For declaring style sheets within a document.</p>
<p><strong><code>&lt;sub></code></strong><span></span> For displaying subscript. Useful for math, especially in conjunction with <code>&lt;sup></code> (superscript).</p>
<p><strong><code>&lt;summary></code></strong><span></span> Used in conjunction with the <code>&lt;details></code> tag for specifying a summary.</p>
<p><strong><code>&lt;sup></code></strong><span></span> For displaying superscript. Useful for math, especially in conjunction with <code>&lt;sub></code> (subscript).</p>
<p><strong><code>&lt;table></code></strong><span></span> For making tables in an <abbr title="Hypertext Markup Language">HTML</abbr> page.</p>
<p><strong><code>&lt;tbody></code></strong><span></span> Groups table rows.</p>
<p><strong><code>&lt;td></code></strong><span></span> Table data; this represents a data cell within a table.</p>
<p><strong><code>&lt;template></code></strong><span></span> Declares <abbr title="Hypertext Markup Language">HTML</abbr> snippets that can be used later.</p>
<p><strong><code>&lt;textarea></code></strong><span></span> For multi-line text entry.</p>
<p><strong><code>&lt;tfoot></code></strong><span></span> Table footer.</p>
<p><strong><code>&lt;th></code></strong><span></span> Table header cell.</p>
<p><strong><code>&lt;thead></code></strong><span></span> Table header row.</p>
<p><strong><code>&lt;time></code></strong><span></span> Specifies the date/time within a document.</p>
<p><strong><a href="/html-page-title-element">&lt;title></a></strong><span></span> The title of an <abbr title="Hypertext Markup Language">HTML</abbr> document.</p>
<p><strong><code>&lt;tr></code></strong><span></span> A row within a table.</p>
<p><strong><code>&lt;track></code></strong><span></span> Used to specify text tracks with <code>&lt;audio></code> and <code>&lt;video></code>.</p>
<p><strong><code>&lt;u></code></strong><span></span> Useful for annotating text for various reasons. No longer specifically for underlining, although you can of course still do that with <abbr title="Cascading Style Sheets">CSS</abbr>.</p>
<p><strong><code>&lt;ul></code></strong><span></span> Unordered list. Use with <code>&lt;li></code> (list item) to make unordered lists.</p>
<p><strong><code>&lt;var></code></strong><span></span> Defines a variable within the content of an <abbr title="Hypertext Markup Language">HTML</abbr> page.</p>
<p><strong><code>&lt;video></code></strong><span></span> For embedding video within an <abbr title="Hypertext Markup Language">HTML</abbr> page.</p>
<p><strong><a href="html-line-break-opportunity-wbr-element">&lt;wbr></a></strong><span></span> The optional line wrap.</p>
</section><?php }
}
